### ISSUE TITLE
Access Tokens via Service Directly

### ISSUE THREAD

**Issue by steinbachio** [Aguafrommars/Maui.Blazor.Authentication#12]
In my case i am using keycloak as the OIDC Server.

Keycloak requires me to send the id_token along with the logout URL.

In the web, i can use JSRuntime to access the session storage and retrieve this token.

Is there a service in this library that can provide me the tokens (access_token and id_token)?

**Comment by aguacongas** [comment]
You can retrieve the stored [`AuthenticationEntity`](https://github.com/Aguafrommars/Maui.Blazor.Authentication/blob/main/src/Aguacongas.AspNetCore.Components.Maui.Authentication.Oidc/Models/AuthenticationEntity.cs) associated to your scope using the `IAuthenticationStore` :

```cs
var settings = sp.GetRequiredService<IOptions<RemoteAuthenticationOptions<OidcProviderOptions>>>().Value;
var store = sp.GetRequiredService<IAuthenticationStore>();
var currentAuthenticationEntity = await store.GetAsync(string.Join(" ", settings.ProviderOptions.DefaultScopes));
var idToken = currentAuthenticationEntity.IdentityToken:
```

**Comment by steinbachio** [comment]
thanks!

**Comment by stylusdotnet** [comment]
Could you elaborate about this solution? I am facing the same issue with keycloak, as it want the id_token_hint in the querystring in the logout url.

Is it possible to interject a parameter to that url in maui blazor hybrid?

Something like

if (kc.idToken) { 
     url += '&id_token_hint=' + encodeURIComponent(kc.idToken); 
 }
