### ISSUE TITLE
Question: How to pass token with Grpc

### ISSUE THREAD

**Issue by Sen-Gupta** [Aguafrommars/Maui.Blazor.Authentication#47]
Hello Olivier,

This is some excellent stuff with lots of details and complexities baked in but simplified.

And extra special congrats for the great work with both the samples. (This is where most people lack).

Just one question, I would like to pass the token with Grpc request or just need the access token to pass with SignalR request?
How do we get the token?

**Comment by aguacongas** [comment]
The [`IAuthenticationStore`](https://github.com/Aguafrommars/Maui.Blazor.Authentication/blob/main/src/Aguacongas.AspNetCore.Components.Maui.Authentication.Oidc/Abstraction/IAuthenticationStore.cs) implementation give you access to the tokens store, you can get a reference from the DI container and call `GetAsync(string scope)` to get stored [`AuthenticationEntity`](https://github.com/Aguafrommars/Maui.Blazor.Authentication/blob/main/src/Aguacongas.AspNetCore.Components.Maui.Authentication.Oidc/Models/AuthenticationEntity.cs) containing tokens for the scope.

```cs
using Aguacongas.AspNetCore.Components.Maui.Authentication.Oidc.Abstraction;
using Microsoft.AspNetCore.Components.WebAssembly.Authentication;

class NeedToken
{
    private readonly IAuthenticationStore  _store;
    private readonly ProviderOptions _options;

    public NeedToken(IAuthenticationStore store, ProviderOptions options)
    {
         _store = store;
         _options = options
    }

    public async Task AuthenticateGrpcRequest(GrpcRequest request) 
    {
         var authenticationEntity = await _store.GetAsync(string.Join(" ", _options.DefaultScopes)).ConfigureAwait(false);
         var accessToken = authenticationEntity.AccessToken;
         request.AccessToken = accessToken;
   }
}
```

**Comment by Sen-Gupta** [comment]
Thanks!
